Initial commit
Ikomia-hub/infer_lama pull request #1
Opened 2022-09-27 08:36 UTC by allankouidri

2022-09-27 13:51 UTC, LudoBar requested changes

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +
Too much line break

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +        self.method = str(param_map["method"])
self.method is a str, no cast needed

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +
2 extra line breaks

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +
1 extra line break. In class, you should have only 1 free line between methods, it's 2 between module functions.

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +
Extra line break -> à checker partout

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +            ratio = np.sqrt(img_limit_size / float(h_orig*w_orig))
ratio n'est pas égal à param.ini_res? Pourquoi refaire ce calcul?

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +            binImg_3d = resize(binImg_3d, (h, w),interpolation='bilinear', align_corners=False)
Attention aux espaces entre les arguments des fonctions -> à checker partout

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +        # Inpainted_img = self.applyGraphicsMask(src_ini, cur_res, 0)
Il faudra penser à verifier que le masque existe; methode C2dImageTask::isMaskAvailable().

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_process.py
> +        self.predict_config_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), "lama-config/predict_config.yaml")
On peut aussi utiliser os.path.join(os.path.dirname(os.path.realpath(__file__)), "lama-config", "predict_config.yaml") pour éviter des mettre les séparateurs de dossiers en dur (/ pour Linux et \ pour Windows)

2022-09-27 13:51 UTC, LudoBar commented on infer_lama_widget.py
> +
Toujours les saut lignes en trop -> à checker partout

2022-09-28 07:58 UTC, ambroiseb commented on infer_lama_process.py
> +        if h_orig* w_orig > img_limit_size:
"if param.ini_res < 100" fait la même chose?

2022-09-28 14:29 UTC, ambroiseb approved these changes

2022-09-28 14:30 UTC, merged